var fs = require('fs');
console.log("Building images...");
console.log("Output directory: " + __pathname__ + " /out/skin");
var brick = [];
// Use stripped game `DATA` cfg file to download all the default skins
var DATA = {
    person: [
        { title: "Beth", id: 420, picture: "https://shadysam.com/wp-content/uploads/person_beth.png", is_a_special: false },
        { title: "Stewart", id: 435, picture: "https://shadysam.com/wp-content/uploads/person_stewart.png", is_a_special: false },
        { title: "Roopali", id: 434, picture: "https://shadysam.com/wp-content/uploads/person_roopali.png", is_a_special: false },
        { title: "Neil", id: 433, picture: "https://shadysam.com/wp-content/uploads/person_neil.png", is_a_special: false },
        { title: "Martha", id: 432, picture: "https://shadysam.com/wp-content/uploads/person_martha.png", is_a_special: false },
        { title: "Mario", id: 431, picture: "https://shadysam.com/wp-content/uploads/person_mario.png", is_a_special: false },
        { title: "Leigh", id: 430, picture: "https://shadysam.com/wp-content/uploads/person_leigh.png", is_a_special: false },
        { title: "Kevin", id: 429, picture: "https://shadysam.com/wp-content/uploads/person_kevin.png", is_a_special: false },
        { title: "Ken", id: 428, picture: "https://shadysam.com/wp-content/uploads/person_ken.png", is_a_special: false },
        { title: "Jaycinda", id: 427, picture: "https://shadysam.com/wp-content/uploads/person_jaycinda.png", is_a_special: false },
        { title: "Fred", id: 426, picture: "https://shadysam.com/wp-content/uploads/person_fred.png", is_a_special: false },
        { title: "Dustin", id: 425, picture: "https://shadysam.com/wp-content/uploads/person_dustin.png", is_a_special: false },
        { title: "Denise", id: 424, picture: "https://shadysam.com/wp-content/uploads/person_denise.png", is_a_special: false },
        { title: "Charlotte", id: 423, picture: "https://shadysam.com/wp-content/uploads/person_charlotte.png", is_a_special: false },
        { title: "Carmen", id: 422, picture: "https://shadysam.com/wp-content/uploads/person_carmen.png", is_a_special: false },
        { title: "Robin", id: 57, picture: "https://shadysam.com/wp-content/uploads/person_robin.png", is_a_special: true },
        { title: "Marcus", id: 290, picture: "https://shadysam.com/wp-content/uploads/person_marcus.png", is_a_special: false },
        { title: "Patrick", id: 289, picture: "https://shadysam.com/wp-content/uploads/person_patrick.png", is_a_special: false },
        { title: "Jerry", id: 287, picture: "https://shadysam.com/wp-content/uploads/person_jerry.png", is_a_special: false },
        { title: "Harper", id: 286, picture: "https://shadysam.com/wp-content/uploads/person_harper.png", is_a_special: false },
        { title: "Elaine", id: 285, picture: "https://shadysam.com/wp-content/uploads/person_elaine.png", is_a_special: false },
        { title: "Diego", id: 284, picture: "https://shadysam.com/wp-content/uploads/person_diego.png", is_a_special: false },
        { title: "Devon", id: 283, picture: "https://shadysam.com/wp-content/uploads/person_devon.png", is_a_special: false },
        { title: "Amy", id: 282, picture: "https://shadysam.com/wp-content/uploads/person_amy.png", is_a_special: false },
        { title: "Ariana", id: 136, picture: "https://shadysam.com/wp-content/uploads/person_ariana.png", is_a_special: false },
        { title: "Jorge", id: 135, picture: "https://shadysam.com/wp-content/uploads/person_jorge.png", is_a_special: false },
        { title: "Myrtle", id: 134, picture: "https://shadysam.com/wp-content/uploads/person_myrtle.png", is_a_special: false },
        { title: "Keisha", id: 133, picture: "https://shadysam.com/wp-content/uploads/person_keisha.png", is_a_special: false },
        { title: "Steven", id: 72, picture: "https://shadysam.com/wp-content/uploads/person_steven.png", is_a_special: true },
        { title: "Gertrude", id: 58, picture: "https://shadysam.com/wp-content/uploads/person_gertrude.png", is_a_special: false },
    ],
    reward: [
        {
            title: "coffee-cup",
            id: 100,
            reward_image: {
                ID: 617,
                id: 617,
                title: "reward_mug",
                filename: "reward_mug.png",
                filesize: 308,
                url: "https://shadysam.com/wp-content/uploads/reward_mug.png",
                link: "https://shadysam.com/reward/coffee-cup/reward_mug/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_mug",
                status: "inherit",
                uploaded_to: 100,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:56:54",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_mug.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "desk-lamp",
            id: 101,
            reward_image: {
                ID: 614,
                id: 614,
                title: "reward_lamp",
                filename: "reward_lamp.png",
                filesize: 503,
                url: "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                link: "https://shadysam.com/reward/desk-lamp/reward_lamp/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_lamp",
                status: "inherit",
                uploaded_to: 101,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:56:45",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_lamp.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "stapler",
            id: 102,
            reward_image: {
                ID: 622,
                id: 622,
                title: "reward_stapler",
                filename: "reward_stapler.png",
                filesize: 296,
                url: "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                link: "https://shadysam.com/reward/stapler/reward_stapler/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_stapler",
                status: "inherit",
                uploaded_to: 102,
                date: "2018-11-05 16:50:39",
                modified: "2018-11-05 16:56:37",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_stapler.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "pencil-cup",
            id: 103,
            reward_image: {
                ID: 620,
                id: 620,
                title: "reward_pencilcup",
                filename: "reward_pencilcup.png",
                filesize: 309,
                url: "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                link: "https://shadysam.com/reward/pencil-cup/reward_pencilcup/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_pencilcup",
                status: "inherit",
                uploaded_to: 103,
                date: "2018-11-05 16:50:39",
                modified: "2018-11-05 16:56:29",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_pencilcup.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "calculator",
            id: 104,
            reward_image: {
                ID: 609,
                id: 609,
                title: "reward_calculator",
                filename: "reward_calculator.png",
                filesize: 255,
                url: "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                link: "https://shadysam.com/reward/calculator/reward_calculator/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_calculator",
                status: "inherit",
                uploaded_to: 104,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:56:21",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_calculator.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "bobble-head",
            id: 105,
            reward_image: {
                ID: 612,
                id: 612,
                title: "reward_dog",
                filename: "reward_dog.png",
                filesize: 325,
                url: "https://shadysam.com/wp-content/uploads/reward_dog.png",
                link: "https://shadysam.com/reward/bobble-head/reward_dog/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_dog",
                status: "inherit",
                uploaded_to: 105,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:56:12",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_dog.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "balls",
            id: 320,
            reward_image: {
                ID: 619,
                id: 619,
                title: "reward_newton",
                filename: "reward_newton.png",
                filesize: 318,
                url: "https://shadysam.com/wp-content/uploads/reward_newton.png",
                link: "https://shadysam.com/reward/balls/reward_newton/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_newton",
                status: "inherit",
                uploaded_to: 320,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:56:03",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_newton.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: "https://shadysam.com/wp-content/uploads/reward_newton_animated.gif",
        },
        {
            title: "cat",
            id: 321,
            reward_image: {
                ID: 611,
                id: 611,
                title: "reward_cat",
                filename: "reward_cat.png",
                filesize: 381,
                url: "https://shadysam.com/wp-content/uploads/reward_cat.png",
                link: "https://shadysam.com/reward/cat/reward_cat/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_cat",
                status: "inherit",
                uploaded_to: 321,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:55:52",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_cat.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: "https://shadysam.com/wp-content/uploads/reward_cat_anim.gif",
        },
        {
            title: "dollar",
            id: 322,
            reward_image: {
                ID: 613,
                id: 613,
                title: "reward_dollar",
                filename: "reward_dollar.png",
                filesize: 338,
                url: "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                link: "https://shadysam.com/reward/dollar/reward_dollar/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_dollar",
                status: "inherit",
                uploaded_to: 322,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:55:40",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_dollar.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "lava",
            id: 323,
            reward_image: {
                ID: 616,
                id: 616,
                title: "reward_lava",
                filename: "reward_lava.png",
                filesize: 381,
                url: "https://shadysam.com/wp-content/uploads/reward_lava.png",
                link: "https://shadysam.com/reward/lava/reward_lava/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_lava",
                status: "inherit",
                uploaded_to: 323,
                date: "2018-11-05 16:50:38",
                modified: "2018-11-05 16:55:32",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_lava.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: "https://shadysam.com/wp-content/uploads/reward_lava_animated.gif",
        },
        {
            title: "trophy",
            id: 324,
            reward_image: {
                ID: 623,
                id: 623,
                title: "reward_trophy",
                filename: "reward_trophy.png",
                filesize: 379,
                url: "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                link: "https://shadysam.com/reward/trophy/reward_trophy/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_trophy",
                status: "inherit",
                uploaded_to: 324,
                date: "2018-11-05 16:50:39",
                modified: "2018-11-05 16:55:20",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_trophy.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
        {
            title: "plant",
            id: 325,
            reward_image: {
                ID: 621,
                id: 621,
                title: "reward_plant",
                filename: "reward_plant.png",
                filesize: 405,
                url: "https://shadysam.com/wp-content/uploads/reward_plant.png",
                link: "https://shadysam.com/reward/plant/reward_plant/",
                alt: "",
                author: "1",
                description: "",
                caption: "",
                name: "reward_plant",
                status: "inherit",
                uploaded_to: 325,
                date: "2018-11-05 16:50:39",
                modified: "2018-11-05 16:55:07",
                menu_order: 0,
                mime_type: "image/png",
                type: "image",
                subtype: "png",
                icon: "https://shadysam.com/wp-includes/images/media/default.png",
                width: 52,
                height: 58,
                sizes: {
                    thumbnail: "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "thumbnail-width": 52,
                    "thumbnail-height": 58,
                    medium: "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "medium-width": 52,
                    "medium-height": 58,
                    medium_large: "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "medium_large-width": 52,
                    "medium_large-height": 58,
                    large: "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "large-width": 52,
                    "large-height": 58,
                    "1536x1536": "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "1536x1536-width": 52,
                    "1536x1536-height": 58,
                    "2048x2048": "https://shadysam.com/wp-content/uploads/reward_plant.png",
                    "2048x2048-width": 52,
                    "2048x2048-height": 58,
                },
            },
            reward_animated: false,
        },
    ],
    game_config: [
        "https://shadysam.com/wp-content/uploads/ms_bg_wall2.png",
        "https://shadysam.com/wp-content/uploads/ms_bg_floor.png",
        "https://shadysam.com/wp-content/uploads/bg_door.png",
        "https://shadysam.com/wp-content/uploads/bg_desk.png",
        "https://shadysam.com/wp-content/uploads/bg_chair.png",
        "https://shadysam.com/wp-content/uploads/bg_computer.gif",
        "https://shadysam.com/wp-content/uploads/bg_wallStuff.png",
        "https://shadysam.com/wp-content/uploads/ms_ui_menuBar_bg.png",
        "https://shadysam.com/wp-content/uploads/bg_loanOptionCardFront.png",
        "https://shadysam.com/wp-content/uploads/bg_loanOptionCardBack-Correct.png",
        "https://shadysam.com/wp-content/uploads/bg_loanOptionCardBack-Incorrect.png",
        "https://shadysam.com/wp-content/uploads/bg_envelope.png",
        "https://shadysam.com/wp-content/uploads/bg_knock.png",
        "https://shadysam.com/wp-content/uploads/ms_ui_wallpaper2.jpg",
        "https://shadysam.com/wp-content/uploads/bg_computer_screen.jpg",
        "https://shadysam.com/wp-content/uploads/ui_rotateDevice.png",
        "https://shadysam.com/wp-content/uploads/bg_vignetteCorner.png",
        "https://shadysam.com/wp-content/uploads/ui_hintTab.png",
        "https://shadysam.com/wp-content/uploads/ui_fullscreen_expand.png",
        "https://shadysam.com/wp-content/uploads/ui_fullscreen_contract.png",
    ],
    title_screen: [
        "https://shadysam.com/wp-content/uploads/title_logo.png",
        "https://shadysam.com/wp-content/uploads/ms_title_bg_wall.png",
        :"https://shadysam.com/wp-content/uploads/title_bg.png",
    ],
    info: [
        "https://shadysam.com/wp-content/uploads/ui_infoIcon.png",
        "https://shadysam.com/wp-content/uploads/info_bg.png",
        "https://shadysam.com/wp-content/uploads/info_close.png",
    ],
    game_over: [
        "https://shadysam.com/wp-content/uploads/ui_sharkRating_open.png",
        "https://shadysam.com/wp-content/uploads/ui_sharkRating_filled.png",
    ],
    social: [
        "https://shadysam.com/wp-content/uploads/shareImg_Facebook.png",
        "https://shadysam.com/wp-content/uploads/shareImg_twitter.png",
        "https://shadysam.com/wp-content/uploads/icon_facebook.png",
        "https://shadysam.com/wp-content/uploads/icon_twitter.png",
    ]
};

// screw this I'll figure it out later
